//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlQueryParsing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SqlQueryParsing.ClientResources", typeof(ClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsflyer.
        /// </summary>
        internal static string AppsFlyerSchemaName {
            get {
                return ResourceManager.GetString("AppsFlyerSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to athena_rawdata_queryhistory.
        /// </summary>
        internal static string AthenaRawDataQueryHistoryTableName {
            get {
                return ResourceManager.GetString("AthenaRawDataQueryHistoryTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to databases.
        /// </summary>
        internal static string DatabasesTableName {
            get {
                return ResourceManager.GetString("DatabasesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fields.
        /// </summary>
        internal static string FieldsTableName {
            get {
                return ResourceManager.GetString("FieldsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fields_with_unclear_path.
        /// </summary>
        internal static string FieldsWithUnclearPath {
            get {
                return ResourceManager.GetString("FieldsWithUnclearPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parsed_queries_field_access_log.
        /// </summary>
        internal static string ParsedQueriesFieldAccessLog {
            get {
                return ResourceManager.GetString("ParsedQueriesFieldAccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queries.
        /// </summary>
        internal static string QueriesTableName {
            get {
                return ResourceManager.GetString("QueriesTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schemas.
        /// </summary>
        internal static string SchemasTableName {
            get {
                return ResourceManager.GetString("SchemasTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tables.
        /// </summary>
        internal static string TablesTableName {
            get {
                return ResourceManager.GetString("TablesTableName", resourceCulture);
            }
        }
    }
}
